version: '3.8'

services:
  smartretail-backend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      bash -c "
      pip install --no-cache-dir -r requirements.txt &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "

  supplier-api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./supplier-api:/app
    ports:
      - "8001:8001"
    command: >
      bash -c "
      pip install --no-cache-dir -r requirements.txt &&
      uvicorn main:app --host 0.0.0.0 --port 8001
      "
